import subprocess, os, datetime
import pandas as pd
import numpy as np
import pytz

# File paths of the tools
MFTECMD = r"MFTECmd.exe"
EVTXECMD = r"EvtxeCmd.exe"
RECMD = r"RECmd.exe"
filefolder = "ExtractedFiles"

# CSV/JSON, but the format will stay fixed to CSV
filetype = "csv"
dateTime = "yyyy-MM-dd HH:mm:ss.fffffff"  # The user cannot change this
drive = "example_files\\C\\"
mftLocation = "example_files\\C\\$MFT"
batchPath = "BatchExamples\\DFIRBatch.reb"
mapPath = ""

# Function to create a unique folder to save output files
def create_unique_directory(base_path="ExtractedFiles\\"):
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    dir_name = os.path.join(base_path, timestamp)
    os.makedirs(dir_name, exist_ok=True)
    return dir_name + "\\"

# Function to normalize timestamp to UTC
def convert_to_utc(timestamp):
    try:
        # Assuming the timestamp format is `yyyy-MM-dd HH:mm:ss.fffffff`
        local_dt = datetime.datetime.strptime(timestamp, "%Y-%m-%d %H:%M:%S.%f")
        # Convert to UTC
        local_dt = local_dt.replace(tzinfo=pytz.UTC)
        return local_dt.strftime("%Y-%m-%d %H:%M:%S.%f UTC")
    except Exception as e:
        return "Invalid Timestamp"

# Function to ensure all necessary columns exist in the DataFrame
def ensure_columns(df, required_columns):
    for col in required_columns:
        if col not in df.columns:
            df[col] = "N/A"
    return df

# Function to add artifact tags to the CSV files
def mark_csv(df, mark, filepath):
    # Adding an additional column for Artifact Source
    df["Artifact Source"] = mark
    # Renaming columns to indicate the source artifact
    df = df.rename(columns={col: col + " " + mark for col in df.columns})
    df.to_csv(filepath, index=False)
    return df

# Function to merge the CSV files from each tool (MFTECmd, EvtxECmd, RECmd)
def merge_csv(folderpath):
    print("Merging CSV Files...")
    try:
        # Load the CSV files generated by each tool
        df_mfte = pd.read_csv(folderpath + "Individual\\mftecmd.csv", low_memory=False)
        df_evtx = pd.read_csv(folderpath + "Individual\\evtxecmd.csv", low_memory=False)
        df_rec = pd.read_csv(folderpath + "Individual\\recmd.csv", low_memory=False)

        # Ensure necessary columns exist in each DataFrame
        df_mfte = ensure_columns(df_mfte, ["Created0x10"])
        df_evtx = ensure_columns(df_evtx, ["TimeCreated"])
        df_rec = ensure_columns(df_rec, ["LastWriteTimestamp"])

        # Normalize the timestamps to UTC
        df_mfte["Normalized Timestamp"] = df_mfte["Created0x10"].apply(convert_to_utc)
        df_evtx["Normalized Timestamp"] = df_evtx["TimeCreated"].apply(convert_to_utc)
        df_rec["Normalized Timestamp"] = df_rec["LastWriteTimestamp"].apply(convert_to_utc)

        # Add artifact tags for clarity
        df_mfte = mark_csv(df_mfte, "(MFTECMD)", folderpath + "Individual\\mftecmd.csv")
        df_evtx = mark_csv(df_evtx, "(EVTXECMD)", folderpath + "Individual\\evtxecmd.csv")
        df_rec = mark_csv(df_rec, "(RECMD)", folderpath + "Individual\\recmd.csv")

        # Merge the DataFrames on the appropriate columns
        df_merged = pd.concat([df_mfte, df_evtx, df_rec], ignore_index=True)

        # Ensure all necessary columns exist in the merged DataFrame
        df_merged = ensure_columns(df_merged, ["Normalized Timestamp", "Artifact Source"])

        # Reorder columns to place 'Normalized Timestamp' and 'Artifact Source' at the front
        df_merged = df_merged[["Normalized Timestamp", "Artifact Source"] + [col for col in df_merged.columns if col not in ["Normalized Timestamp", "Artifact Source"]]]

        # Save the merged DataFrame as a CSV file
        df_merged.to_csv(folderpath + "merged_file.csv", index=False)

        print("Merge complete. Saved as merged_file.csv")
    except FileNotFoundError:
        print("Error: One or more CSV files not found.")
    except Exception as e:
        print("Error during merge:", e)

# Function to execute the extraction and merging
def execute():
    folderpath = create_unique_directory()

    # Execute the tools to extract data
    print("Executing RECmd...")
    subprocess.Popen(f"RECmd.exe -d {drive} --bn {batchPath} --{filetype} {folderpath}Individual\\ --dt \"{dateTime}\" --csvf recmd.csv", shell=True).wait()

    print("Executing MFTECmd...")
    subprocess.Popen(f"MFTECmd.exe -f {mftLocation} -m {mftLocation} --{filetype} {folderpath}Individual\\ --dt \"{dateTime}\" --csvf mftecmd.csv", shell=True).wait()

    print("Executing EvtxECmd...")
    subprocess.Popen(f"EvtxECmd.exe -d {drive} --{filetype} {folderpath}Individual\\ {mapPath} --dt \"{dateTime}\" --csvf evtxecmd.csv", shell=True).wait()

    # Wait for the tools to finish extracting data
    print("All data is being extracted, please wait...")
    merge_csv(folderpath)
    print(f"Output folder: {folderpath}")

# Main function to run the program
def main():
    print("Mini Project 2")
    print("List of tools combined (3): ")
    print("1. MFTECmd")
    print("2. EvtxECmd")
    print("3. RECmd")
    
    merged()

if __name__ == "__main__":
    main()
